### List all files saved in database:
GET http://localhost:8080
Accept: application/json

### Upload content from JSON body as a `README.txt` file:
POST http://localhost:8080
Content-Type: application/json
Accept: application/json

{
  "name": "README.txt",
  "content": "Hello!"
}

### Upload `README.md` file using IDEA HTTP request REST client:
POST http://localhost:8080/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="README.md"

// The 'README.md' file will be uploaded
< ./README.md

### Upload `pom.xml` file using IDEA HTTP request REST client:
POST http://localhost:8080/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="pom.xml"

// The 'README.md' file will be uploaded
< ./pom.xml

###
